### ISSUE TITLE
Reporting error with `AccountBase`

### ISSUE THREAD

**Issue by mikedotexe** [AbstractSDK/abstract.js#38]
Query failed with (6): rpc error: code = Unknown desc = failed to execute message; message index: 0: abstract_core::native::version_control::AccountBase not found: execute wasm contract failed [CosmWasm/wasmd@v0.45.0/x/wasm/keeper/keeper.go:395] With gas wanted: '100000000' and gas used: '98074' : unknown request

I thought I'd share a little giffy

![abstract-error](https://github.com/AbstractSDK/abstract.js/assets/1042667/f140e796-0ba2-450d-99ea-b9857f243fa5)

It might be in the frontend code (couldn't find a repo) using this, dunno ❤️

**Comment by dalechyn** [comment]
> Query failed with (6): rpc error: code = Unknown desc = failed to execute message; message index: 0: abstract_core::native::version_control::AccountBase not found: execute wasm contract failed [CosmWasm/wasmd@v0.45.0/x/wasm/keeper/keeper.go:395] With gas wanted: '100000000' and gas used: '98074' : unknown request
> 
> I thought I'd share a little giffy
> 
> ![abstract-error](https://private-user-images.githubusercontent.com/1042667/299869357-f140e796-0ba2-450d-99ea-b9857f243fa5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NDcwMzMsIm5iZiI6MTcwNjU0NjczMywicGF0aCI6Ii8xMDQyNjY3LzI5OTg2OTM1Ny1mMTQwZTc5Ni0wYmEyLTQ1MGQtOTllYS1iOTg1N2YyNDNmYTUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjlUMTY0NTMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmU4YjM5YmQ5YzI2MjRkMDgzMjA0YjZiNThhZTRkODliNGZjOTI0MzBlYTkwODJiYTY1ZGYxYzk3YWQ2MWI5ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3ZJOJSno_rwyEYE2mbtvuP7T_r0mgIVJ0h80WTEyFkA) [ ![abstract-error](https://private-user-images.githubusercontent.com/1042667/299869357-f140e796-0ba2-450d-99ea-b9857f243fa5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NDcwMzMsIm5iZiI6MTcwNjU0NjczMywicGF0aCI6Ii8xMDQyNjY3LzI5OTg2OTM1Ny1mMTQwZTc5Ni0wYmEyLTQ1MGQtOTllYS1iOTg1N2YyNDNmYTUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjlUMTY0NTMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmU4YjM5YmQ5YzI2MjRkMDgzMjA0YjZiNThhZTRkODliNGZjOTI0MzBlYTkwODJiYTY1ZGYxYzk3YWQ2MWI5ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3ZJOJSno_rwyEYE2mbtvuP7T_r0mgIVJ0h80WTEyFkA) ](https://private-user-images.githubusercontent.com/1042667/299869357-f140e796-0ba2-450d-99ea-b9857f243fa5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NDcwMzMsIm5iZiI6MTcwNjU0NjczMywicGF0aCI6Ii8xMDQyNjY3LzI5OTg2OTM1Ny1mMTQwZTc5Ni0wYmEyLTQ1MGQtOTllYS1iOTg1N2YyNDNmYTUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjlUMTY0NTMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmU4YjM5YmQ5YzI2MjRkMDgzMjA0YjZiNThhZTRkODliNGZjOTI0MzBlYTkwODJiYTY1ZGYxYzk3YWQ2MWI5ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3ZJOJSno_rwyEYE2mbtvuP7T_r0mgIVJ0h80WTEyFkA)
> 
> It might be in the frontend code (couldn't find a repo) using this, dunno ❤️

Thanks for sharing! This is indeed a wrong repo but thank you very much for the bug report, the issue was forwarded to the console team.

Join Abstract Discord (https://discord.gg/uch3Tq3aym) for further involvement, thanks!
